import {
    Box,
    Button,
    Card,
    CardContent,
    CardHeader,
    Container,
    Stack,
    TextField,
    Typography,
    useTheme,
} from '@mui/material'
import Head from 'next/head'

import Navbar from '../src/components/Header/NavbarMobil'
import ThemeUpdater from '../src/components/Header/ThemeUpdater'

export default function Home() {
    const theme = useTheme()

    return (
        <Container
            sx={{
                backgroundColor: theme.palette.primary.main,
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                width: '100%',
                maxWidth: '100%',
            }}
        >
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Card sx={{ width: '340px' }} variant={'disabled'}>
                    <CardHeader title="01" />
                    <CardContent></CardContent>
                </Card>
                <Typography variant="h1">Heading</Typography>
                <Typography variant="body1">Test</Typography>

                <Stack spacing={2} direction="row">
                    <Button variant="contained">Contained</Button>
                    <Button variant="outlined">Outlined</Button>
                    <Button variant="text">Text</Button>
                </Stack>

                <Box>
                    <TextField
                        id="standard-basic"
                        label="Standard"
                        variant="standard"
                    />
                </Box>
                {/* <ThemeUpdater /> */}
            </main>

            <footer></footer>
        </Container>
    )
}
